# Site settings

# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            CMU Mars Studios
tagline:          'Spring 2016'
description:      'Two spring interdisciplinary courses at CMU are investigating the future of space exploration.'
-- url:              http://2015.cmumarsstudios.com
baseurl:          /marsstudio

author:
  name:           'Daragh Byrne &amp; Christina Christina Ciardullo'
  url:            http://daraghbyrne.github.io/marsstudio/

email: daragh@daraghbyrne.me
twitter_username: cmumarsstudios
github_username:  daraghbyrne

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/daraghbyrne/cmumarsstudio
